spring:
  application:
    name: hello-world
server:
  port: 8081
  servlet:
    context-path: /hello-world

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
